server:
  port: 8080

spring:
  application:
    name: synapse-oauth
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: "${clientId}"
            client-secret: "${clientSecret}"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - openid

        provider:
          cognito:
            issuer-uri: "https://cognito-idp.${region}.amazonaws.com/${userPoolId}"
            user-name-attribute: "sub"

      resourceserver:
        jwt:
          issuer-uri: "https://cognito-idp.${region}.amazonaws.com/${userPoolId}"

app:
  cognito:
    domain: "${cognitoDomain}"